In [115]:
import pandas as pd
import numpy as np

TD=pd.read_csv("trip_data.csv", header=0, skip_blank_lines=False,parse_dates=['Start Date','End Date'],date_parser=lambda d: pd.to_datetime(d, format="%d/%m/%Y %H:%M", errors="coerce"))
WD=pd.read_csv("weather_data.csv", header=0, skip_blank_lines=False,parse_dates=['Date'],date_parser=lambda d: pd.to_datetime(d, format="%d/%m/%Y", errors="coerce"))
SD=pd.read_csv("station_data.csv", header=0, skip_blank_lines=False)

In [116]:
TD.head(30)

,Trip ID,Start Date,Start Station,End Date,End Station,Subscriber Type
0,913460,2015-08-31 23:26:00,50,2015-08-31 23:39:00,70,Subscriber
1,913459,2015-08-31 23:11:00,31,2015-08-31 23:28:00,27,Subscriber
2,913455,2015-08-31 23:13:00,47,2015-08-31 23:18:00,64,Subscriber
3,913454,2015-08-31 23:10:00,10,2015-08-31 23:17:00,8,Subscriber
4,913453,2015-08-31 23:09:00,51,2015-08-31 23:22:00,60,Customer
5,913452,2015-08-31 23:07:00,68,2015-08-31 23:12:00,70,Subscriber
6,913451,2015-08-31 23:07:00,51,2015-08-31 23:22:00,60,Customer
7,913450,2015-08-31 22:16:00,60,2015-08-31 22:20:00,74,Subscriber
8,913449,2015-08-31 22:12:00,56,2015-08-31 22:15:00,55,Subscriber
9,913448,2015-08-31 21:57:00,47,2015-08-31 22:12:00,66,Subscriber
10,913443,2015-08-31 21:49:00,60,2015-08-31 22:01:00,77,Subscriber
11,913442,2015-08-31 21:44:00,67,2015-08-31 21:54:00,70,Subscriber
12,913441,2015-08-31 21:39:00,76,2015-08-31 21:46:00,73,Subscriber
13,913440,2015-08-31 21:31:00,77,2015-08-31 21:36:00,82,Subscriber
14,913435,2015-08-31 21:25:00,55,2015-08-31 21:33:00,88,Subscriber
15,913434,2015-08-31 21:19:00,88,2015-08-31 21:24:00,65,Subscriber
16,913433,2015-08-31 21:17:00,35,2015-08-31 21:20:00,37,Customer
17,913432,2015-08-31 21:16:00,87,2015-08-31 21:28:00,88,Subscriber
18,913431,2015-08-31 21:11:00,55,2015-08-31 21:21:00,73,Subscriber
19,913429,2015-08-31 21:07:00,70,2015-08-31 21:22:00,82,Subscriber
20,913426,2015-08-31 21:06:00,70,2015-08-31 21:14:00,76,Subscriber
21,913421,2015-08-31 21:01:00,28,2015-08-31 21:07:00,32,Subscriber
22,913419,2015-08-31 20:58:00,74,2015-08-31 21:10:00,70,Subscriber
23,913416,2015-08-31 20:53:00,68,2015-08-31 20:59:00,88,Subscriber
24,913415,2015-08-31 20:53:00,50,2015-08-31 20:58:00,54,Subscriber
25,913410,2015-08-31 20:46:00,60,2015-08-31 20:58:00,54,Subscriber
26,913409,2015-08-31 20:44:00,87,2015-08-31 20:52:00,61,Subscriber
27,913404,2015-08-31 20:39:00,88,2015-08-31 20:44:00,65,Subscriber
28,913403,2015-08-31 20:37:00,77,2015-08-31 20:45:00,61,Subscriber
29,913402,2015-08-31 20:36:00,67,2015-08-31 20:43:00,57,Subscriber

In [117]:
conditions = [
    (SD['City']=='San Jose'),
    (SD['City']=='Mountain View'),
    (SD['City']=='Palo Alto'),
    (SD['City']=='San Francisco'),
    (SD['City']=='Redwood City')]
     
choices = [95113, 94041, 94301,94107,94063]
SD['Zip'] = np.select(conditions, choices)

conditions = [
    (TD['Start Station']==23),
    (TD['Start Station']==25),
    (TD['Start Station']==49),
    (TD['Start Station']==69),
    (TD['Start Station']==72),
    (TD['Start Station']==89),
    (TD['Start Station']!=23&25&49&69&72&89)] 
choices = [85,86, 87,88,90,90,TD['Start Station']]
TD['Start Station'] = np.select(conditions, choices)

conditions=[
    (TD['End Station']==23),
    (TD['End Station']==25),
    (TD['End Station']==49),
    (TD['End Station']==69),
    (TD['End Station']==72),
    (TD['End Station']==89),
    (TD['End Station']!=23&25&49&69&72&89)]
choices = [85,86, 87,88,90,90,TD['End Station']]
TD['End Station'] = np.select(conditions, choices)

In [118]:
SD.head()

,Id,Name,Lat,Long,Dock Count,City,Zip
0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,San Jose,95113
1,3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,95113
2,4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,95113
3,5,Adobe on Almaden,37.331415,-121.893200,19,San Jose,95113
4,6,San Pedro Square,37.336721,-121.894074,15,San Jose,95113

In [119]:
TD['Start Date Truncated']=TD['Start Date'].dt.floor('h')
TD['End Date Truncated']=TD['End Date'].dt.floor('h')
TD.head()

,Trip ID,Start Date,Start Station,End Date,End Station,Subscriber Type,Start Date Truncated,End Date Truncated
0,913460,2015-08-31 23:26:00,50,2015-08-31 23:39:00,70,Subscriber,2015-08-31 23:00:00,2015-08-31 23:00:00
1,913459,2015-08-31 23:11:00,31,2015-08-31 23:28:00,27,Subscriber,2015-08-31 23:00:00,2015-08-31 23:00:00
2,913455,2015-08-31 23:13:00,47,2015-08-31 23:18:00,64,Subscriber,2015-08-31 23:00:00,2015-08-31 23:00:00
3,913454,2015-08-31 23:10:00,10,2015-08-31 23:17:00,8,Subscriber,2015-08-31 23:00:00,2015-08-31 23:00:00
4,913453,2015-08-31 23:09:00,51,2015-08-31 23:22:00,60,Customer,2015-08-31 23:00:00,2015-08-31 23:00:00

In [120]:
WD.head()

,Date,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,Zip
0,2014-09-01,83.0,70.0,57.0,58.0,56.0,52.0,86.0,64.0,42.0,...,10.0,8.0,16.0,7.0,20.0,0.0,0.0,NaN,290.0,94107
1,2014-09-02,72.0,66.0,60.0,58.0,57.0,55.0,84.0,73.0,61.0,...,10.0,7.0,21.0,8.0,NaN,0.0,5.0,NaN,290.0,94107
2,2014-09-03,76.0,69.0,61.0,57.0,56.0,55.0,84.0,69.0,53.0,...,10.0,10.0,21.0,8.0,24.0,0.0,4.0,NaN,276.0,94107
3,2014-09-04,74.0,68.0,61.0,57.0,57.0,56.0,84.0,71.0,57.0,...,10.0,8.0,22.0,8.0,25.0,0.0,5.0,NaN,301.0,94107
4,2014-09-05,72.0,66.0,60.0,57.0,56.0,54.0,84.0,71.0,57.0,...,9.0,7.0,18.0,8.0,32.0,0.0,4.0,NaN,309.0,94107

In [121]:
TD_bystation_bystartdate = (pd.DataFrame(TD.groupby(['Start Station','Start Date Truncated'])
                            ['Start Date Truncated']
                            .count()         
                            .fillna(0)))
TD_bystation_bystartdate.columns=['Start Count']
TD_bystation_bystartdate.reset_index(inplace=True)
TD_bystation_bystartdate.head()

   Start Station Start Date Truncated  Start Count
0              2  2014-09-01 12:00:00            1
1              2  2014-09-01 21:00:00            4
2              2  2014-09-01 22:00:00            1
3              2  2014-09-02 01:00:00            1
4              2  2014-09-02 07:00:00            3

In [122]:
TD_bystation_byenddate = (pd.DataFrame(TD.groupby(['End Station','End Date Truncated'])
                            ['End Date Truncated']
                            .count()         
                            .fillna(0)))
TD_bystation_byenddate.columns=['End Count']
TD_bystation_byenddate.reset_index(inplace=True)
TD_bystation_byenddate.head()

   End Station  End Date Truncated  End Count
0            2 2014-09-01 14:00:00          1
1            2 2014-09-02 06:00:00          3
2            2 2014-09-02 07:00:00          6
3            2 2014-09-02 08:00:00          1
4            2 2014-09-02 09:00:00          2

In [123]:
DFstation=SD['Id']

In [124]:
DFtime=pd.date_range(start=TD_bystation_byenddate['End Date Truncated'].min(), end=TD_bystation_byenddate['End Date Truncated'].max(), freq='h')

In [125]:
DFMerge=pd.MultiIndex.from_product([DFstation,DFtime],names=['Station','Time'])
DFMerge=pd.DataFrame(index=DFMerge).reset_index()

In [126]:
DFMerge.head()

   Station                Time
0        2 2014-09-01 00:00:00
1        2 2014-09-01 01:00:00
2        2 2014-09-01 02:00:00
3        2 2014-09-01 03:00:00
4        2 2014-09-01 04:00:00

In [127]:
DFall=pd.merge(left=DFMerge, right=TD_bystation_bystartdate, how='left', on=None, left_on=['Station','Time'], right_on=['Start Station','Start Date Truncated'])
DFall=pd.merge(left=DFall, right=TD_bystation_byenddate, how='left', on=None, left_on=['Station','Time'], right_on=['End Station','End Date Truncated'])

In [128]:
DFall.to_csv("DFall_after2merges.csv")

KeyboardInterrupt:

In [129]:
DFall.shape

(665760, 8)

In [130]:
DFall=DFall.drop(columns=['Start Station','Start Date Truncated','End Station','End Date Truncated'])
DFall=DFall.fillna(0)
DFall.head()

   Station                Time  Start Count  End Count
0        2 2014-09-01 00:00:00          0.0        0.0
1        2 2014-09-01 01:00:00          0.0        0.0
2        2 2014-09-01 02:00:00          0.0        0.0
3        2 2014-09-01 03:00:00          0.0        0.0
4        2 2014-09-01 04:00:00          0.0        0.0

In [131]:
DFall['Net Bikes Per Hour']=DFall['End Count']-DFall['Start Count']
DFall.head(25)

    Station                Time  Start Count  End Count  Net Bikes Per Hour
0         2 2014-09-01 00:00:00          0.0        0.0                 0.0
1         2 2014-09-01 01:00:00          0.0        0.0                 0.0
2         2 2014-09-01 02:00:00          0.0        0.0                 0.0
3         2 2014-09-01 03:00:00          0.0        0.0                 0.0
4         2 2014-09-01 04:00:00          0.0        0.0                 0.0
5         2 2014-09-01 05:00:00          0.0        0.0                 0.0
6         2 2014-09-01 06:00:00          0.0        0.0                 0.0
7         2 2014-09-01 07:00:00          0.0        0.0                 0.0
8         2 2014-09-01 08:00:00          0.0        0.0                 0.0
9         2 2014-09-01 09:00:00          0.0        0.0                 0.0
10        2 2014-09-01 10:00:00          0.0        0.0                 0.0
11        2 2014-09-01 11:00:00          0.0        0.0                 0.0
12        2 2014-09-01 12:00:00          1.0        0.0                -1.0
13        2 2014-09-01 13:00:00          0.0        0.0                 0.0
14        2 2014-09-01 14:00:00          0.0        1.0                 1.0
15        2 2014-09-01 15:00:00          0.0        0.0                 0.0
16        2 2014-09-01 16:00:00          0.0        0.0                 0.0
17        2 2014-09-01 17:00:00          0.0        0.0                 0.0
18        2 2014-09-01 18:00:00          0.0        0.0                 0.0
19        2 2014-09-01 19:00:00          0.0        0.0                 0.0
20        2 2014-09-01 20:00:00          0.0        0.0                 0.0
21        2 2014-09-01 21:00:00          4.0        0.0                -4.0
22        2 2014-09-01 22:00:00          1.0        0.0                -1.0
23        2 2014-09-01 23:00:00          0.0        0.0                 0.0
24        2 2014-09-02 00:00:00          0.0        0.0                 0.0

In [132]:
DFall.shape

(665760, 5)

In [133]:
DFtemp=pd.merge(left=DFall, right=SD, how='left', left_on=['Station'], right_on=['Id'])
DFall=DFtemp

In [134]:
DFall['Date']=DFall['Time'].dt.floor('D')
DFall.shape

(665760, 13)

In [135]:
WD['DateTrunc']=WD['Date'].dt.floor('D')

In [136]:
WD['DateTrunc'].min()

Timestamp('2014-09-01 00:00:00')

In [137]:
DFfinal=pd.merge(left=DFall, right=WD, how='left', on=['Zip','Date'],indicator=True)
DFall.shape

(665760, 13)

In [138]:
DFfinal.head(300)

,Station,Time,Start Count,End Count,Net Bikes Per Hour,Id,Name,Lat,Long,Dock Count,...,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,DateTrunc,_merge
0,2,2014-09-01 00:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
1,2,2014-09-01 01:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
2,2,2014-09-01 02:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
3,2,2014-09-01 03:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
4,2,2014-09-01 04:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
5,2,2014-09-01 05:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
6,2,2014-09-01 06:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
7,2,2014-09-01 07:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
8,2,2014-09-01 08:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
9,2,2014-09-01 09:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
10,2,2014-09-01 10:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
11,2,2014-09-01 11:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
12,2,2014-09-01 12:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
13,2,2014-09-01 13:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
14,2,2014-09-01 14:00:00,0.0,1.0,1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
15,2,2014-09-01 15:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
16,2,2014-09-01 16:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
17,2,2014-09-01 17:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
18,2,2014-09-01 18:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
19,2,2014-09-01 19:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
20,2,2014-09-01 20:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
21,2,2014-09-01 21:00:00,4.0,0.0,-4.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
22,2,2014-09-01 22:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
23,2,2014-09-01 23:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,10.0,17.0,5.0,22.0,0.0,0.0,NaN,296.0,2014-09-01,both
24,2,2014-09-02 00:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,9.0,15.0,6.0,20.0,0.0,0.0,NaN,300.0,2014-09-02,both
25,2,2014-09-02 01:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,9.0,15.0,6.0,20.0,0.0,0.0,NaN,300.0,2014-09-02,both
26,2,2014-09-02 02:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,9.0,15.0,6.0,20.0,0.0,0.0,NaN,300.0,2014-09-02,both
27,2,2014-09-02 03:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,9.0,15.0,6.0,20.0,0.0,0.0,NaN,300.0,2014-09-02,both
28,2,2014-09-02 04:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,9.0,15.0,6.0,20.0,0.0,0.0,NaN,300.0,2014-09-02,both
29,2,2014-09-02 05:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,9.0,15.0,6.0,20.0,0.0,0.0,NaN,300.0,2014-09-02,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2,2014-09-12 06:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
271,2,2014-09-12 07:00:00,5.0,0.0,-5.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
272,2,2014-09-12 08:00:00,3.0,0.0,-3.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
273,2,2014-09-12 09:00:00,3.0,0.0,-3.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
274,2,2014-09-12 10:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
275,2,2014-09-12 11:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
276,2,2014-09-12 12:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
277,2,2014-09-12 13:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
278,2,2014-09-12 14:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
279,2,2014-09-12 15:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
280,2,2014-09-12 16:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
281,2,2014-09-12 17:00:00,2.0,0.0,-2.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
282,2,2014-09-12 18:00:00,2.0,0.0,-2.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
283,2,2014-09-12 19:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
284,2,2014-09-12 20:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
285,2,2014-09-12 21:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
286,2,2014-09-12 22:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
287,2,2014-09-12 23:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,6.0,13.0,4.0,22.0,0.0,1.0,NaN,299.0,2014-09-12,both
288,2,2014-09-13 00:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
289,2,2014-09-13 01:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
290,2,2014-09-13 02:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
291,2,2014-09-13 03:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
292,2,2014-09-13 04:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
293,2,2014-09-13 05:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
294,2,2014-09-13 06:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
295,2,2014-09-13 07:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
296,2,2014-09-13 08:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
297,2,2014-09-13 09:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
298,2,2014-09-13 10:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
299,2,2014-09-13 11:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both

In [105]:
WD.to_csv("WD after parse.csv")

In [52]:
print(DFall['Zip'].unique())
print(WD['Zip'].unique())

[95113 94063 94041 94301 94107]
[94107 94063 94301 94041 95113]

In [80]:
import missingno as msno
msno.matrix(DFall)

ModuleNotFoundError: No module named 'missingno'

In [82]:
DFall.head(300)

,Station,Time,Start Count,End Count,Net Bikes Per Hour,Id,Name,Lat,Long,Dock Count,...,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,DateTrunc,_merge
0,2,2014-09-01 00:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
1,2,2014-09-01 01:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
2,2,2014-09-01 02:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
3,2,2014-09-01 03:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
4,2,2014-09-01 04:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
5,2,2014-09-01 05:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
6,2,2014-09-01 06:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
7,2,2014-09-01 07:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
8,2,2014-09-01 08:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
9,2,2014-09-01 09:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
10,2,2014-09-01 10:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
11,2,2014-09-01 11:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
12,2,2014-09-01 12:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
13,2,2014-09-01 13:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
14,2,2014-09-01 14:00:00,0.0,1.0,1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
15,2,2014-09-01 15:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
16,2,2014-09-01 16:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
17,2,2014-09-01 17:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
18,2,2014-09-01 18:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
19,2,2014-09-01 19:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
20,2,2014-09-01 20:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
21,2,2014-09-01 21:00:00,4.0,0.0,-4.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
22,2,2014-09-01 22:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
23,2,2014-09-01 23:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
24,2,2014-09-02 00:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
25,2,2014-09-02 01:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
26,2,2014-09-02 02:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
27,2,2014-09-02 03:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
28,2,2014-09-02 04:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
29,2,2014-09-02 05:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2,2014-09-12 06:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
271,2,2014-09-12 07:00:00,5.0,0.0,-5.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
272,2,2014-09-12 08:00:00,3.0,0.0,-3.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
273,2,2014-09-12 09:00:00,3.0,0.0,-3.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
274,2,2014-09-12 10:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
275,2,2014-09-12 11:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
276,2,2014-09-12 12:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
277,2,2014-09-12 13:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
278,2,2014-09-12 14:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
279,2,2014-09-12 15:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
280,2,2014-09-12 16:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
281,2,2014-09-12 17:00:00,2.0,0.0,-2.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
282,2,2014-09-12 18:00:00,2.0,0.0,-2.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
283,2,2014-09-12 19:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
284,2,2014-09-12 20:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
285,2,2014-09-12 21:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
286,2,2014-09-12 22:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
287,2,2014-09-12 23:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,8.0,12.0,3.0,15.0,0.0,6.0,NaN,116.0,2014-09-12,both
288,2,2014-09-13 00:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
289,2,2014-09-13 01:00:00,1.0,0.0,-1.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
290,2,2014-09-13 02:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
291,2,2014-09-13 03:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
292,2,2014-09-13 04:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
293,2,2014-09-13 05:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
294,2,2014-09-13 06:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
295,2,2014-09-13 07:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
296,2,2014-09-13 08:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
297,2,2014-09-13 09:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
298,2,2014-09-13 10:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both
299,2,2014-09-13 11:00:00,0.0,0.0,0.0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,...,7.0,14.0,5.0,20.0,0.0,4.0,NaN,296.0,2014-09-13,both

In [ ]:
DFall.to_csv("DFall_afterAllmerges.csv")

In [ ]:




#Import column of station IDs into a data frame
DFstation<-as_data_frame(SD$Id)
#Create column of date/times from beginning to end of , sequentially by hour
DF<-as_data_frame(seq(from=min(TD$Start.Date.Truncated), to=max(TD$End.Date.Truncated), by="hours"))
#Cross join station ID and sequential date/time columns so that every permutation is created
DFall<-merge(x=DFstation, y=DF, by=NULL)
colnames(DFall)<- c("Station","Date")
rm(DFstation, DF)

#Import hourly data of bikes leaving and entering each station into its relevant date/time and station row
DFall<-left_join(DFall, TD_bystation_bystartdate, by=c("Station","Date"))
DFall<-left_join(DFall, TD_bystation_byenddate, by=c("Station","Date"))
DFall[is.na(DFall)] <- 0

#Net change of number of bikes per hour is calculated: CountNet
DFall$CountNet=DFall$CountStart+DFall$CountEnd
#Import station information
DFall<-left_join(DFall, SD, by=c("Station"="Id"))

DFall$Date_Trunc=floor_date(DFall$Date, unit = "day")

#Import weather data
DFall<-left_join(DFall, WD, by=c("Date_Trunc"="Date", "CityZip"="Zip"))
#Extract hour, weekday, and month data from date/time column
DFall$hour=hour(DFall$Date)
DFall$wday=wday(DFall$Date)
DFall$month=month(DFall$Date)
DFall$absCountNet=abs(DFall$CountNet)

In [58]:
DFall.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 665760 entries, 0 to 665759
Data columns (total 13 columns):
Station               665760 non-null int64
Time                  665760 non-null datetime64[ns]
Start Count           665760 non-null float64
End Count             665760 non-null float64
Net Bikes Per Hour    665760 non-null float64
Id                    665760 non-null int64
Name                  665760 non-null object
Lat                   665760 non-null float64
Long                  665760 non-null float64
Dock Count            665760 non-null int64
City                  665760 non-null object
Zip                   665760 non-null int64
Date                  665760 non-null datetime64[ns]
dtypes: datetime64[ns](2), float64(5), int64(4), object(2)
memory usage: 71.1+ MB

In [57]:
WD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 25 columns):
Date                         1825 non-null datetime64[ns]
Max TemperatureF             1821 non-null float64
Mean TemperatureF            1821 non-null float64
Min TemperatureF             1821 non-null float64
Max Dew PointF               1775 non-null float64
MeanDew PointF               1775 non-null float64
Min DewpointF                1775 non-null float64
Max Humidity                 1775 non-null float64
Mean Humidity                1775 non-null float64
Min Humidity                 1775 non-null float64
Max Sea Level PressureIn     1824 non-null float64
Mean Sea Level PressureIn    1824 non-null float64
Min Sea Level PressureIn     1824 non-null float64
Max VisibilityMiles          1820 non-null float64
Mean VisibilityMiles         1820 non-null float64
Min VisibilityMiles          1820 non-null float64
Max Wind SpeedMPH            1824 non-null float64
Mean Wind SpeedMPH           1824 non-null float64
Max Gust SpeedMPH            1284 non-null float64
PrecipitationIn              1824 non-null float64
CloudCover                   1824 non-null float64
Events                       287 non-null object
WindDirDegrees               1824 non-null float64
Zip                          1825 non-null int64
DateTrunc                    1825 non-null datetime64[ns]
dtypes: datetime64[ns](2), float64(21), int64(1), object(1)
memory usage: 356.5+ KB

In [56]:
SD.dtypes

Id              int64
Name           object
Lat           float64
Long          float64
Dock Count      int64
City           object
Zip             int64
dtype: object